export const paths = {
  root: '/',
  login: '/login',
  signup: '/signup',
  forgotPassword: '/forgot-password',
  leads: '/leads',
  analytics: '/analytics',
  addLead: '/leads/new',
  headersConfig: '/configuration/headers',
  projectsList: '/configuration/projects',
  apiList: '/configuration/api',
  bookingForm: '/configuration/booking',
  resources: '/configuration/resources',
  whatsapp: '/configuration/whatsapp',
  organization: '/organization',
  users: '/users',
  contactsList: '/leads/contacts',
  tasksList: '/leads/tasks',
  callLogsList: '/leads/calls',
  bookingsList: '/leads/bookings',
  sortedList: '/leads/sorted',
  newsList: '/support/news',
  faqList: '/support/faq',
  licenses: '/account/licenses',
  coupons: '/account/coupons',
  updatePassword: '/account/password',
} as const